package(default_visibility = ["//visibility:public"])

cc_library(
    name = "camera_hal",
    srcs = ["camera_hal.cpp"],
    hdrs = ["camera_hal.h"],
    deps = ["//mediapipe/framework/port:opencv_highgui",
        "//mediapipe/framework/port:opencv_imgproc",
        "//mediapipe/framework/port:opencv_video",],
)