licenses(["notice"])

package(default_visibility = ["//visibility:public"])


cc_binary(
    name = "gesture_game",
    srcs = ["main.cpp"],
    deps = [
        "//bazel_project_build/app:gesture",
        "//bazel_project_build/app:RoomManager",
        "//bazel_project_build/app:WebSocketClient",
        "//bazel_project_build/app:WebSocketReceiver",
    ],
)

